version: '2'

services:
  python3.8:
    build:
      context: .
      dockerfile: python3.8.dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - "./:/var/perestroika/"
    command: bash -c "coverage run --source='./perestroika/' -m pytest tests -vv && coverage combine && coverage report"

  python3.7:
    build:
      context: .
      dockerfile: python3.7.dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - "./:/var/perestroika/"
    command: bash -c "coverage run --source='./perestroika/' -m pytest tests -vv && coverage combine && coverage report"
